-- MySQL Script generated by MySQL Workbench
-- Sun Jan  8 00:20:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 13_books_core
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 13_books_core
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `13_books_core` DEFAULT CHARACTER SET utf8mb3 ;
USE `13_books_core` ;

-- -----------------------------------------------------
-- Table `13_books_core`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `13_books_core`.`books` (
  `idBooks` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idBooks`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `13_books_core`.`fav_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `13_books_core`.`fav_books` (
  `idFav_Books` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `author` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idFav_Books`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `13_books_core`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `13_books_core`.`authors` (
  `idAuthors` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(45) NULL DEFAULT NULL,
  `Fav_Books_idFav_Books` INT NOT NULL,
  `Books_idBooks` INT NOT NULL,
  PRIMARY KEY (`idAuthors`),
  INDEX `fk_Authors_Fav_Books1_idx` (`Fav_Books_idFav_Books` ASC) VISIBLE,
  INDEX `fk_Authors_Books1_idx` (`Books_idBooks` ASC) VISIBLE,
  CONSTRAINT `fk_Authors_Books1`
    FOREIGN KEY (`Books_idBooks`)
    REFERENCES `13_books_core`.`books` (`idBooks`),
  CONSTRAINT `fk_Authors_Fav_Books1`
    FOREIGN KEY (`Fav_Books_idFav_Books`)
    REFERENCES `13_books_core`.`fav_books` (`idFav_Books`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `13_books_core`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `13_books_core`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Fav_Books_idFav_Books` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Fav_Books_idx` (`Fav_Books_idFav_Books` ASC) VISIBLE,
  CONSTRAINT `fk_User_Fav_Books`
    FOREIGN KEY (`Fav_Books_idFav_Books`)
    REFERENCES `13_books_core`.`fav_books` (`idFav_Books`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
